theme: jekyll-theme-cayman
title: Kathleen Yi
name: Kathleen Yi
markdown: kramdown
description: Currently a master's student studying machine learning and applied statistics with previous experience in biotechnology research and lab automation.
