theme: jekyll-theme-cayman
title: Welcome to Kathleen's homepage!
name: Kathleen Yi
markdown: kramdown
description: Currently a master's student studying machine learning and applied statistics with previous experience in biotechnology research and lab automation.
